//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSalud.srTriaje {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srTriaje.wsTriajeSoap")]
    public interface wsTriajeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string IdTriaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string IdTriaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTriajeSoapChannel : ClienteSalud.srTriaje.wsTriajeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTriajeSoapClient : System.ServiceModel.ClientBase<ClienteSalud.srTriaje.wsTriajeSoap>, ClienteSalud.srTriaje.wsTriajeSoap {
        
        public wsTriajeSoapClient() {
        }
        
        public wsTriajeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTriajeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTriajeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTriajeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura) {
            return base.Channel.Agregar(IdTriaje, Dni, Talla, Sintomas, Peso, Temperatura);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura) {
            return base.Channel.AgregarAsync(IdTriaje, Dni, Talla, Sintomas, Peso, Temperatura);
        }
        
        public string[] Actualizar(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura) {
            return base.Channel.Actualizar(IdTriaje, Dni, Talla, Sintomas, Peso, Temperatura);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdTriaje, string Dni, string Talla, string Sintomas, string Peso, string Temperatura) {
            return base.Channel.ActualizarAsync(IdTriaje, Dni, Talla, Sintomas, Peso, Temperatura);
        }
        
        public string[] Eliminar(string IdTriaje) {
            return base.Channel.Eliminar(IdTriaje);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string IdTriaje) {
            return base.Channel.EliminarAsync(IdTriaje);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
