//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSalud.srHistorial {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srHistorial.wsHistorialSoap")]
    public interface wsHistorialSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string IdHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string IdHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsHistorialSoapChannel : ClienteSalud.srHistorial.wsHistorialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsHistorialSoapClient : System.ServiceModel.ClientBase<ClienteSalud.srHistorial.wsHistorialSoap>, ClienteSalud.srHistorial.wsHistorialSoap {
        
        public wsHistorialSoapClient() {
        }
        
        public wsHistorialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsHistorialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsHistorialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsHistorialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta) {
            return base.Channel.Agregar(IdHistorial, Dni, UltimaFechadeEntrada, UltimaFechadeAlta, CodMedico, IdConsultorio, IdReceta);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta) {
            return base.Channel.AgregarAsync(IdHistorial, Dni, UltimaFechadeEntrada, UltimaFechadeAlta, CodMedico, IdConsultorio, IdReceta);
        }
        
        public string[] Actualizar(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta) {
            return base.Channel.Actualizar(IdHistorial, Dni, UltimaFechadeEntrada, UltimaFechadeAlta, CodMedico, IdConsultorio, IdReceta);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdHistorial, string Dni, string UltimaFechadeEntrada, string UltimaFechadeAlta, string CodMedico, string IdConsultorio, string IdReceta) {
            return base.Channel.ActualizarAsync(IdHistorial, Dni, UltimaFechadeEntrada, UltimaFechadeAlta, CodMedico, IdConsultorio, IdReceta);
        }
        
        public string[] Eliminar(string IdHistorial) {
            return base.Channel.Eliminar(IdHistorial);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string IdHistorial) {
            return base.Channel.EliminarAsync(IdHistorial);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
