//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSalud.srMedico {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srMedico.wsMedicoSoap")]
    public interface wsMedicoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string CodMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string CodMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsMedicoSoapChannel : ClienteSalud.srMedico.wsMedicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsMedicoSoapClient : System.ServiceModel.ClientBase<ClienteSalud.srMedico.wsMedicoSoap>, ClienteSalud.srMedico.wsMedicoSoap {
        
        public wsMedicoSoapClient() {
        }
        
        public wsMedicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsMedicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsMedicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsMedicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad) {
            return base.Channel.Agregar(CodMedico, NombreMedico, ApellidoMedico, IdEspecialidad);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad) {
            return base.Channel.AgregarAsync(CodMedico, NombreMedico, ApellidoMedico, IdEspecialidad);
        }
        
        public string[] Actualizar(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad) {
            return base.Channel.Actualizar(CodMedico, NombreMedico, ApellidoMedico, IdEspecialidad);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string CodMedico, string NombreMedico, string ApellidoMedico, string IdEspecialidad) {
            return base.Channel.ActualizarAsync(CodMedico, NombreMedico, ApellidoMedico, IdEspecialidad);
        }
        
        public string[] Eliminar(string CodMedico) {
            return base.Channel.Eliminar(CodMedico);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string CodMedico) {
            return base.Channel.EliminarAsync(CodMedico);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
