//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSalud.srPaciente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srPaciente.wsPacienteSoap")]
    public interface wsPacienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string Dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string Dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPacienteSoapChannel : ClienteSalud.srPaciente.wsPacienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPacienteSoapClient : System.ServiceModel.ClientBase<ClienteSalud.srPaciente.wsPacienteSoap>, ClienteSalud.srPaciente.wsPacienteSoap {
        
        public wsPacienteSoapClient() {
        }
        
        public wsPacienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPacienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPacienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPacienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento) {
            return base.Channel.Agregar(Dni, NombrePaciente, ApellidoPaciente, Direccion, Genero, FechaNacimiento);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento) {
            return base.Channel.AgregarAsync(Dni, NombrePaciente, ApellidoPaciente, Direccion, Genero, FechaNacimiento);
        }
        
        public string[] Actualizar(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento) {
            return base.Channel.Actualizar(Dni, NombrePaciente, ApellidoPaciente, Direccion, Genero, FechaNacimiento);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string Dni, string NombrePaciente, string ApellidoPaciente, string Direccion, string Genero, string FechaNacimiento) {
            return base.Channel.ActualizarAsync(Dni, NombrePaciente, ApellidoPaciente, Direccion, Genero, FechaNacimiento);
        }
        
        public string[] Eliminar(string Dni) {
            return base.Channel.Eliminar(Dni);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string Dni) {
            return base.Channel.EliminarAsync(Dni);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
