//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSalud.srLaboratorio {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srLaboratorio.wsLaboratorioSoap")]
    public interface wsLaboratorioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string Idlab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string Idlab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsLaboratorioSoapChannel : ClienteSalud.srLaboratorio.wsLaboratorioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsLaboratorioSoapClient : System.ServiceModel.ClientBase<ClienteSalud.srLaboratorio.wsLaboratorioSoap>, ClienteSalud.srLaboratorio.wsLaboratorioSoap {
        
        public wsLaboratorioSoapClient() {
        }
        
        public wsLaboratorioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsLaboratorioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLaboratorioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLaboratorioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico) {
            return base.Channel.Agregar(Idlab, TipoLab, NombreLab, Dni, Resultado, CodMedico);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico) {
            return base.Channel.AgregarAsync(Idlab, TipoLab, NombreLab, Dni, Resultado, CodMedico);
        }
        
        public string[] Actualizar(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico) {
            return base.Channel.Actualizar(Idlab, TipoLab, NombreLab, Dni, Resultado, CodMedico);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string Idlab, string TipoLab, string NombreLab, string Dni, string Resultado, string CodMedico) {
            return base.Channel.ActualizarAsync(Idlab, TipoLab, NombreLab, Dni, Resultado, CodMedico);
        }
        
        public string[] Eliminar(string Idlab) {
            return base.Channel.Eliminar(Idlab);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string Idlab) {
            return base.Channel.EliminarAsync(Idlab);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
